apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: simple-web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web-server
  template:
    metadata:
      labels:
        app: simple-web-server
    spec:
      containers:
      - name: simple-web-server
        image: nnekic/appzaprojekat-1:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
