name: ci
on:
  push:
    branches: [main]
jobs:
  testing:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: compile Java
        run: javac AppZaProjekat.java   
      - name: run Java app
        run: java AppZaProjekat &
      - name: testing server
        run: |
          sleep 5
          curl -f http://localhost:8081/

  push_to_docker_hub:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to the DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t nnekic/appzaprojekat#1:latest .
      - name: Push to the docker hub
        run: docker push nnekic/appzaprojekat#1:latest

