name: ci
on:
  push:
    branches: [main]
jobs:
  testing:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: compile Java
        run: javac AppZaProjekat.java   
      - name: run Java app
        run: java AppZaProjekat
